spring:
  application:
    name: discovery-server

eureka:
  registration:
    enabled: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8761